# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          image: hashicorp/terraform:1.1.4
          name: 'Download dependencies'
          script:
            - terrform init
          caches:
            - docker
          artifacts:
              - ./**
      - step:
          name: 'Get config file'
          script:
            - echo "Getting config file..."
      - step:
          name: 'Test'
          script:
            - echo "Your Test goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Plan changes'
        deployment: staging
        caches:
          - docker
        script:
          - terraform plan
    - step:
        name: 'Apply changes'
        deployment: production
        caches:
          - docker
        trigger: 'manual'
        script:
          - terraform apply
