# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: hashicorp/terraform:1.1.4

pipelines:
  default:
    - parallel:
      - step:
          name: 'Get config file'
          script:
            - git clone git@bitbucket.org:warnerb47/configuration.git
            - cp configuration/aws/aws-vm-config.yml ./aws/config.yml
            - cd aws
            - terraform init
            - terraform plan
      - step:
          name: 'Test'
          script:
            - echo "Your Test goes here..."
  
  branches:
    run:
      # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
      - step:
          name: 'Plan changes'
          deployment: staging
          script:
            - cd aws
            - terraform init
            - terraform plan
      - step:
          name: 'Apply changes'
          deployment: production
          trigger: 'manual'
          script:
            - cd aws
            - terraform init
            - terraform apply -auto-approve
